# numpy

In [15]:
import numpy as np

In [16]:
list1=[[1,2,3],[4,5,6]]

In [17]:
list1[0][1]

2

In [18]:
print(id(list1),id(list1[0][1]))
list1[0][1]=100
print(id(list1),id(list1[0][1]))

139910913039936 139911272094032
139910913039936 139911272285648


In [19]:
print(type(list1[0][1]))

<class 'int'>


In [20]:
arr=np.array([[1,2,3],[4,5,6]])

In [21]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
#it will print number of dimention
print(arr.ndim)

2


In [23]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(id(arr),id(arr[0][1]))
arr[0][1]=100
print(id(arr),id(arr[0][1]))
print(arr)

139910912674000 139910912713200
139910912674000 139910912712752
[[  1 100   3]
 [  4   5   6]]


In [24]:
print(help(np.int32))

Help on class int32 in module numpy:

class int32(signedinteger)
 |  Signed integer type, compatible with C ``int``.
 |  
 |  :Character code: ``'i'``
 |  :Canonical name: `numpy.intc`
 |  :Alias on this platform: `numpy.int32`: 32-bit signed integer (``-2_147_483_648`` to ``2_147_483_647``).
 |  
 |  Method resolution order:
 |      int32
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(sel

In [25]:
print(type(arr[0][1]))

<class 'numpy.int64'>


In [26]:
arr=np.array([["1","2","3"],["4","5","6"]])

In [27]:
print(id(arr),id(arr[0][1]))
arr[0][1]="100"
print(id(arr),id(arr[0][1]))

139910912876592 139910912877072
139910912876592 139910912877072


# operations

In [28]:
import numpy as np

In [29]:
arr_1d=np.arange(1,11)

In [30]:
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
arr_1d=arr_1d+3

In [32]:
print(arr_1d)

[ 4  5  6  7  8  9 10 11 12 13]


In [33]:
arr_1d=np.arange(1,11)
print(arr_1d)
arr_1d=arr_1d-3
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10]
[-2 -1  0  1  2  3  4  5  6  7]


In [34]:
arr_1d=arr_1d*3

In [35]:
print(arr_1d)

[-6 -3  0  3  6  9 12 15 18 21]


In [36]:
arr_1d=np.arange(1,11)

In [37]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr_2d=arr_1d.reshape(2,5)

In [39]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
arr_2d=arr_1d.reshape(5,-1)
# here selecting (2,-1) will tell numpy python to reshape the array in two rows and column as upon respectively fit.
# this happen when big number of array and we have to reshape into respective dimension of array. row are given but column didn't .
# then we can use -1 to let python numpy select the number of column

In [41]:
print(arr_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [42]:
#we can also convert the 1d array by below method. there is no neccecssary to provide the last column index. we can 
# just use as -1 to let python select respective fit.
arr_2d.shape=2,5

In [43]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
arr_2d.shape=5,-1

In [45]:
print(arr_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [46]:
arr_2d.shape=-1,5

In [47]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [48]:
import numpy as np

In [49]:
#for Defining 3d array
#for defining 3d array, it should be on the way like (x,y,z)
# x represent how many diffrent array you want 
# y represent row and z represents column
arr_1d=np.arange(1,25)
print(arr_1d)
arr_3d=arr_1d.reshape(3,2,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [50]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [51]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
#it is broadcasting like range of arr_2d will increase by 3.
print(arr_2d)
arr_2d+3

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [54]:
#in here list[1,2,3,4,5] will be add in both of the row in arr_2d. it will work only on condition when adding data is have same number of rows and column
print(arr_2d)
arr_2d+[1,2,3,4,5]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [60]:
arr_2d+[1,2,3]

ValueError: operands could not be broadcast together with shapes (2,5) (3,) 

In [61]:
arr_2d+[1,2]

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [55]:
#in here we are adding two different list [1],[2]. thats why it is working
arr_2d+[[1],[2]]

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12]])

# append, insert and delete

In [72]:
arr_1d=np.arange(1,21)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [73]:
#here we are appending the value 11 which simply add inside that array. It will not broadcast the fist and last point 
np.append(arr_1d,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 11])

In [74]:
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [76]:
np.append(arr_1d,[21,22])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [78]:
arr_2d=arr_1d.reshape(4,5)
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [56]:
# here is what happended when you append any element inside an array,
#it will simply convert it to 1d array and then add the element inside.
print(arr_2d)
np.append(arr_2d,3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3])

In [80]:
np.append(arr_2d,[21,22,23,24,25])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [99]:
#here it will append in each column as per we have given the axis point
np.append(arr_2d,[[21,22,23,24,25]],axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [100]:
#here it will append in each row as per we have given the axis point
np.append(arr_2d,[[21],[22],[23],[24]],axis=1)

array([[ 1,  2,  3,  4,  5, 21],
       [ 6,  7,  8,  9, 10, 22],
       [11, 12, 13, 14, 15, 23],
       [16, 17, 18, 19, 20, 24]])

In [101]:
arr_1d=np.arange(1,21)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [57]:
#in here it will insert as per given point.
print(np.insert(arr_1d,0,100))

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


In [103]:
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [58]:
#here python consider that insert element is not a list but element so it will be point as one and insert at one given place.
print(np.insert(arr_1d,3,[100,200]))

[  1   2   3 100 200   4   5   6   7   8   9  10  11  12  13  14  15  16
  17  18  19  20  21  22  23  24]


In [105]:
arr_2d=arr_1d.reshape(4,5)
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [106]:
arr_2d[0]

array([1, 2, 3, 4, 5])

In [107]:
#here it will convert it to 1d array and then add it.
print(np.insert(arr_2d,1,100))

[  1 100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20]


In [108]:
print(np.insert(arr_2d,1,[100,200]))

[  1 100 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16
  17  18  19  20]


In [109]:
#here it will add as per given axis and 2d array will not convert to any other.
print(np.insert(arr_2d,1,[100,200,300,400,500],axis=0))

[[  1   2   3   4   5]
 [100 200 300 400 500]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [115]:
print(np.insert(arr_2d,1,[[100],[200],[300],[400],[500]],axis=0))

[[  1   2   3   4   5]
 [100 100 100 100 100]
 [200 200 200 200 200]
 [300 300 300 300 300]
 [400 400 400 400 400]
 [500 500 500 500 500]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [113]:
print(np.insert(arr_2d,1,[[100,200,300,400]],axis=1))

[[  1 100   2   3   4   5]
 [  6 200   7   8   9  10]
 [ 11 300  12  13  14  15]
 [ 16 400  17  18  19  20]]


In [114]:
print(np.insert(arr_2d,1,[[100],[200],[300],[400]],axis=1))

[[  1 100 200 300 400   2   3   4   5]
 [  6 100 200 300 400   7   8   9  10]
 [ 11 100 200 300 400  12  13  14  15]
 [ 16 100 200 300 400  17  18  19  20]]


In [112]:
print(help(np.insert))

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [116]:
arr_1d=np.arange(1,21)

In [117]:
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [118]:
#it will simply delete the element at given index point.
np.delete(arr_1d,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [119]:
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [121]:
arr_2d=arr_1d.reshape(4,5)
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [122]:
np.delete(arr_2d,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [123]:
np.delete(arr_2d,1,axis=0)

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [124]:
np.delete(arr_2d,1,axis=1)

array([[ 1,  3,  4,  5],
       [ 6,  8,  9, 10],
       [11, 13, 14, 15],
       [16, 18, 19, 20]])

In [131]:
arr_2d=np.arange(1,21).reshape(4,-1)

In [132]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [133]:
arr_2d*arr_2d

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400]])

In [134]:
np.dot(arr_2d,arr_2d)

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [135]:
arr_2d*np.arange(1,5)

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [136]:
arr_1d=np.arange(1,11)

In [137]:
arr_1d*arr_1d

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [138]:
np.dot(arr_1d,arr_1d)

385

# Basic functions

In [142]:
# arr_1d will stroe random 20 integers range between 1 to 10.
arr_1d=np.random.randint(1,10,20)
print(arr_1d)

[5 5 1 8 8 7 3 9 9 8 5 5 7 6 1 5 7 7 6 7]


In [143]:
#this will give minimum value from arr_1d
np.min(arr_1d)

1

In [144]:
#this will show index of min element in arr_1d
np.argmin(arr_1d)

2

In [145]:
#this will give maximum value from arr_1d
np.max(arr_1d)

9

In [146]:
#this will show index of max element in arr_1d
np.argmax(arr_1d)

7

In [147]:
#This will give me the sum of all element inside arr_1d.
np.sum(arr_1d)

119

In [65]:
arr_2d=arr_1d.reshape(4,6)
print(arr_2d.shape)

(3, 8)


In [149]:
print(arr_2d)

[[5 5 1 8 8]
 [7 3 9 9 8]
 [5 5 7 6 1]
 [5 7 7 6 7]]


In [150]:
np.min(arr_2d)

1

In [151]:
np.argmin(arr_2d)

2

In [68]:
print(arr_2d)
print(np.max(arr_2d))
np.argmax(arr_2d)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
24


23

In [69]:
print(arr_2d)
np.min(arr_2d,axis=0)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [155]:
np.min(arr_2d,axis=1)

array([1, 3, 1, 5])

In [156]:
np.argmin(arr_2d,axis=0)

array([0, 1, 0, 2, 2], dtype=int64)

In [157]:
#it is the sum of element column wise . means up to down every column
np.sum(arr_2d,axis=0)

array([22, 20, 24, 29, 24])

In [158]:
print(arr_1d)

[5 5 1 8 8 7 3 9 9 8 5 5 7 6 1 5 7 7 6 7]


In [160]:
arr_1d>5

array([False, False, False,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True, False, False,  True,  True,
        True,  True])

In [161]:
arr_1d[arr_1d>5]

array([8, 8, 7, 9, 9, 8, 7, 6, 7, 7, 6, 7])

In [162]:
arr_1d[arr_1d>5 and arr_1d<8]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [71]:
arr_1d_new=arr_1d[arr_1d>5]
print(arr_1d_new)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [72]:
print(arr_1d_new)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [73]:
arr_1d_newAgain=arr_1d_new[arr_1d_new<8]

In [74]:
print(arr_1d_newAgain)

[6 7]


In [ ]:
[100,200,220,320]

In [167]:
print(arr_1d)

[5 5 1 8 8 7 3 9 9 8 5 5 7 6 1 5 7 7 6 7]


In [169]:
#it is asking that is there any element which is smaller and equal to 9. any keyword work exactly like it means
np.any(arr_1d>=9)

True

In [170]:
#it is asking that all element are smaller and equall to 9
np.all(arr_1d>=9)

False

In [172]:
list(filter(lambda x: x>5 and x<8,arr_1d))

[7, 7, 6, 7, 7, 6, 7]

# indexing and slicing

In [173]:
arr_1d=np.arange(1,10)

In [174]:
print(arr_1d)

[1 2 3 4 5 6 7 8 9]


In [175]:
arr_1d[2]

3

In [176]:
arr_1d[1::2]

array([2, 4, 6, 8])

In [177]:
arr_2d=np.arange(1,21).reshape(4,5)

In [178]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [179]:
arr_2d[1]

array([ 6,  7,  8,  9, 10])

In [180]:
arr_2d[1][1]

7

In [75]:
# this is working in that way like [1::2] . mean go to index(1) and jump to 2th row after current position . 
print(arr_2d)
arr_2d[1::2]

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


array([[ 9, 10, 11, 12, 13, 14, 15, 16]])

In [185]:
arr_2d[1::2][1::2]

array([[16, 17, 18, 19, 20]])

In [187]:
arr_2d[1::2,1::2]

array([[ 7,  9],
       [17, 19]])

# splitting

In [83]:
arr_1d=np.arange(1,10)

In [84]:
#here splitting into given part (3) will be possible when no else elment remain outside of splitting. 
#suppose we are having array (1,11)means 10 element and so , we can't split 10 element into three part . bcz 1 will remain unsplitted.
print(np.split(arr_1d,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [190]:
np.split(arr_1d,4)

ValueError: array split does not result in an equal division

In [191]:
print(arr_1d)

[1 2 3 4 5 6 7 8 9]


In [90]:
np.split(arr_1d,[1,5])

[array([1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]

In [88]:
print(arr_2d)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


In [89]:
np.split(arr_2d,4)

ValueError: array split does not result in an equal division

In [197]:
np.split(arr_2d,5)

ValueError: array split does not result in an equal division

In [199]:
np.split(arr_2d,5,axis=1)

[array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]]),
 array([[ 5],
        [10],
        [15],
        [20]])]

In [200]:
np.split(arr_2d,[1,3])

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]])]

In [201]:
# vectorize
#this program for add elements of two list if it is even multiply otherwise add.
list1=[1,2,3,4,5]
list2=[1,2,3,4,5]

ans=[]
for i in range(0,len(list1)):
    if(i%2==0):
        ans=ans+[list1[i]+list2[i]]
    else:
        ans=ans+[list1[i]*list2[i]]
print(ans)

[2, 4, 6, 16, 10]


In [202]:
#here we are doing by defining a function and by calling it returns the value.
def func_add_mul(a,b,index):
    if(index%2==0):
        return a+b
    else:
        return a*b

In [203]:
#here object_1 contains . vectorize function which will simplay vectorize it 
object_1=np.vectorize(func_add_mul)

In [205]:
#we are calling the function stored variable object_1
print(object_1(np.arange(1,6),np.arange(1,6),np.arange(0,5)))

[ 2  4  6 16 10]


In [206]:
# iteratio of the two-d-arrays
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [207]:
for i in arr_2d:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


In [209]:
for i in arr_2d:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [210]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [213]:
for j in range(0,len(arr_2d[0])):
    for i in range(0,len(arr_2d)):
        print(arr_2d[i][j])
#         arr_2d[i][j]=arr_2d[i][j]*arr_2d[i][j]
        

1
6
11
16
2
7
12
17
3
8
13
18
4
9
14
19
5
10
15
20


In [215]:
for i in np.nditer(arr_2d):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [217]:
for i in np.nditer(arr_2d,order="F"):
    print(i)

1
6
11
16
2
7
12
17
3
8
13
18
4
9
14
19
5
10
15
20


In [221]:
for i in np.nditer(arr_2d,op_flags=["readwrite"]):
    i[...]=i*i

In [222]:
for i in np.nditer(arr_2d):
    print(i)

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400


In [219]:
help(np.nditer)

Help on class nditer in module numpy:

class nditer(builtins.object)
 |  nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)
 |  
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |  
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * ``common_dtype`` causes all the operands to be converted to

In [223]:
arr_1d=np.random.randint(1,100,20)

In [224]:
print(arr_1d)

[91 15 32 74 46 47 99 74 13 53 61 82 95 20 28 55 98 85 88 80]


In [225]:
#it will sort the element in increasing wise
print(np.sort(arr_1d))

[13 15 20 28 32 46 47 53 55 61 74 74 80 82 85 88 91 95 98 99]


In [226]:
arr_1d[arr_1d%3==0]

array([15, 99])

In [227]:
np.where(arr_1d%3==0)

(array([1, 6], dtype=int64),)

In [228]:
import pandas as pd

In [246]:
river_lst = ['Missouri', 'Mississippi', 'Yukon', 
         'Tennessee', 'Brazos', 'Ganges']

In [231]:
series_list=pd.Series(river_lst)

In [232]:
print(series_list)

0       Missouri
1    Mississippi
2          Yukon
3      Tennessee
4         Brazos
5         Ganges
dtype: object


In [234]:
print(series_list[2])

Yukon


In [235]:
print(series_list.index)

RangeIndex(start=0, stop=6, step=1)


In [236]:
series_list.index=["river_"+str(i) for i in range(1,7)]

In [237]:
print(series_list.index)

Index(['river_1', 'river_2', 'river_3', 'river_4', 'river_5', 'river_6'], dtype='object')


In [238]:
print(series_list[2])

Yukon


In [239]:
print(series_list["river_2"])

Mississippi


In [240]:
series_list.index=["a","b","c","d","e","f"]

In [241]:
print(series_list.index)

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')


In [242]:
print(series_list["a"])

Missouri


In [243]:
series_list.index=["a","b","a","d","e","f"]

In [244]:
print(series_list["a"])

a    Missouri
a       Yukon
dtype: object


In [245]:
print(series_list["b":"a"])

KeyError: "Cannot get right slice bound for non-unique label: 'a'"

In [247]:
series_list=pd.Series(river_lst)

In [248]:
print(series_list)

0       Missouri
1    Mississippi
2          Yukon
3      Tennessee
4         Brazos
5         Ganges
dtype: object


In [249]:
series_list[0:4:1]

0       Missouri
1    Mississippi
2          Yukon
3      Tennessee
dtype: object

In [250]:
series_list.index=["a","b","c","d","e","f"]

In [251]:
print(series_list)

a       Missouri
b    Mississippi
c          Yukon
d      Tennessee
e         Brazos
f         Ganges
dtype: object


In [252]:
series_list["a":"e"]

a       Missouri
b    Mississippi
c          Yukon
d      Tennessee
e         Brazos
dtype: object

In [253]:
brics_country = ['Brazil', 'Russia', 'India', 'China', 'South Africa']
brics_currency = ['Real', 'Ruble', 'Rupee', 'Renminbi', 'Rand' ]


In [256]:
Country_currency_series=pd.Series(brics_currency,index=brics_country)

In [257]:
print(Country_currency_series)

Brazil              Real
Russia             Ruble
India              Rupee
China           Renminbi
South Africa        Rand
dtype: object


In [258]:
print(Country_currency_series["China"])

Renminbi


In [260]:
a={"First Name":"Garvit","Last Name":"Taneja"}

In [261]:
series=pd.Series(a)

In [262]:
print(series)

First Name    Garvit
Last Name     Taneja
dtype: object


In [263]:
series=pd.Series(a,index=["First Name","Company","Last Name"])

In [264]:
print(series)

First Name    Garvit
Company          NaN
Last Name     Taneja
dtype: object


In [266]:
series["Company"]="Salesforce"

In [267]:
print(series)

First Name        Garvit
Company       Salesforce
Last Name         Taneja
dtype: object
