In [1]:
import pickle

In [2]:
a={"Garvit":"Taneja","Priya":"Wadhwa"}

In [4]:
with open("today.txt","w+") as f:
    f.write(a)

TypeError: write() argument must be str, not dict

In [5]:
with open("today.txt","w+") as f:
    f.write(str(a))

In [6]:
with open("today.txt","r") as f:
    content=f.read()
print(content,type(content))

{'Garvit': 'Taneja', 'Priya': 'Wadhwa'} <class 'str'>


In [7]:
content["Garvit"]

TypeError: string indices must be integers

In [10]:
import pickle
with open("today.txt","w+b") as f:
    pickle.dump(a,f)

In [11]:
with open("today.txt","r+b") as f:
    content=pickle.load(f)
print(content,type(content))

{'Garvit': 'Taneja', 'Priya': 'Wadhwa'} <class 'dict'>


In [12]:
content["Garvit"]

'Taneja'

# regex

In [13]:
# regex=>regular expression

In [ ]:
"Garvit Pragya Rehan Garvit "

In [14]:
import re

In [ ]:

.       - Any Character Except New Line
\d      - Digit (0-9)
\D      - Not a Digit (0-9)
\w      - Alphanumeric Character (a-z, A-Z, 0-9, _)
\W      - Non Alphanumeric Character
\s      - Whitespace (space, tab, newline)
\S      - Not Whitespace (anything but space, tab, newline)

\b      - Word Boundary ( all the characters except \w (a-z, A-Z, 0-9, _))
\B      - Not a Word Boundary
^       - Beginning of a String
$       - End of a String

[A-Za-z]   - Matches one Characters in brackets
[^A-Z]  - Matches Characters NOT in brackets
|       - Either Or
(com|net)     - Group

Quantifiers:
*       - 0 or More
+       - 1 or More
?       - 0 or One
{3}     - Exact Number
{3,6}   - Range of Numbers (Minimum, Maximum)

In [ ]:
.
\d
\D
"pant in a pantry  apantary"
\bpant

In [ ]:
"text"+[12]
"text"+[a-zA-Z]
"text"+[^ a]
"text"+(gmail.com|yahoo.com)

In [ ]:
a aa aaa aaaa aaaa aaaa 

In [ ]:
b+
a+




In [ ]:
a?
a{3}

In [ ]:
"abcd\nefgh"

In [ ]:
.

In [41]:
content='''9at 9bt Cat c9T mat bat rat hat
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
guptaabhishek.com
abhishek-8765-gupta@yahoo.com
abhi_gyupta@gamil.abc
321-555-4321
123.555.1234
123*555*1234
123.555.1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
abhsihek.gupta@gmail.com
abhishek-1234gupta@gmail.org
abhishek@hotmail.net'''

In [33]:
# match=>it gives us only first occurence of the pattern
# it gives us the occurence only at the begining of the string
ans=re.match(r"\d\w{2}",content)

In [34]:
print(ans)
# print(ans.group())
# print(ans.span())
# print(ans.start())
# print(ans.end())

<re.Match object; span=(0, 3), match='9at'>


In [39]:
# search=>it gives us only first occurence of the pattern
# it gives us the occurence anywhere in the string
ans=re.search(r"\d\w{2}",content)

In [40]:
print(ans)
print(ans.group())
print(ans.span())
print(ans.start())
print(ans.end())

<re.Match object; span=(4, 7), match='9bt'>
9bt
(4, 7)
4
7


In [44]:
#findall
ans=re.findall(r"\d\w{2}",content)

In [45]:
print(ans)
# print(ans.group())
# print(ans.span())
# print(ans.start())
# print(ans.end())

['9at', '9bt', '321', '555', '432', '123', '456', '789', '876', '321', '555', '432', '123', '555', '123', '123', '555', '123', '123', '555', '123', '800', '555', '123', '900', '555', '123', '123', '4gu']


In [52]:
ans=re.finditer(r"\d\w{2}",content)

In [53]:
for i in ans:
    print(i.group())

9at
9bt
321
555
432
123
456
789
876
321
555
432
123
555
123
123
555
123
123
555
123
800
555
123
900
555
123
123
4gu


In [ ]:
content='''9at 9bt Cat c9T mat bat rat hat
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
guptaabhishek.com
abhishek-8765-gupta@yahoo.com
abhi_gyupta@gamil.abc
321-555-4321
123.555.1234
123*555*1234
123.555.1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
abhsihek.gupta@gmail.com
abhishek-1234gupta@gmail.org
abhishek@hotmail.net'''

In [68]:
'''9at 9bt Cat c9T mat bat rat hat\n
abcdefghijklmnopqurtuvwxyz'''
ans=re.finditer(r"\D.*",content)


In [69]:
for i in ans:
    print(i.group())
    print("----")

at 9bt Cat c9T mat bat rat hat
----

abcdefghijklmnopqurtuvwxyz
----

ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
----

321-555-4321
----

1234567890
----

Ha HaHa
----

MetaCharacters (Need to be escaped):
----

. ^ $ * + ? { } [ ] \ | ( )
----

guptaabhishek.com
----

abhishek-8765-gupta@yahoo.com
----

abhi_gyupta@gamil.abc
----

321-555-4321
----

123.555.1234
----

123*555*1234
----

123.555.1234
----

800-555-1234
----

900-555-1234
----

Mr. Schafer
----

Mr Smith
----

Ms Davis
----

Mrs. Robinson
----

Mr. T
----

Mr_hello
----

abhsihek.gupta@gmail.com
----

abhishek-1234gupta@gmail.org
----

abhishek@hotmail.net
----


In [63]:
ans=re.finditer(r"\D.+",content)

In [64]:
for i in ans:
    print(i.group())
    print("------")

at 9bt Cat c9T mat bat rat hat
------

abcdefghijklmnopqurtuvwxyz
------

ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
------

321-555-4321
------

1234567890
------

Ha HaHa
------

MetaCharacters (Need to be escaped):
------

. ^ $ * + ? { } [ ] \ | ( )
------

guptaabhishek.com
------

abhishek-8765-gupta@yahoo.com
------

abhi_gyupta@gamil.abc
------

321-555-4321
------

123.555.1234
------

123*555*1234
------

123.555.1234
------

800-555-1234
------

900-555-1234
------

Mr. Schafer
------

Mr Smith
------

Ms Davis
------

Mrs. Robinson
------

Mr. T
------

Mr_hello
------

abhsihek.gupta@gmail.com
------

abhishek-1234gupta@gmail.org
------

abhishek@hotmail.net
------


In [90]:
content='''9at 9bt Cat c9T mat bat rat hat aab abab
abcdefghijklmnopqurtuvwxyz'''
ans=re.finditer(r"(ab){2}.",content)
# abb
# abab

In [91]:
for i in ans:
    print(i.group())

abab


In [92]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
guptaabhishek.com
abhishek-8765-gupta@yahoo.com
abhi_gyupta@gamil.abc
321-555-4321
123.555.1234
123*555*1234
123.555.1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
abhsihek.gupta@gmail.com
abhishek-1234gupta@gmail.org
abhishek@hotmail.net
'''

In [94]:
# there should be "." and after .there must be either com or net or org
# there should be @ and there should be atleast one character before the @ and one character between @ and .

In [96]:
ans=re.finditer(r".+@.+\.com",text_to_search)

In [97]:
for i in ans:
    print(i.group())

abhishek-8765-gupta@yahoo.com
abhsihek.gupta@gmail.com


In [98]:
ans=re.finditer(r".+@.+\.org",text_to_search)

In [99]:
for i in ans:
    print(i.group())


abhishek-1234gupta@gmail.org


In [100]:
ans=re.finditer(r".+@.+\.(com|net|org)",text_to_search)

In [101]:
for i in ans:
    print(i.group())


abhishek-8765-gupta@yahoo.com
abhsihek.gupta@gmail.com
abhishek-1234gupta@gmail.org
abhishek@hotmail.net


In [ ]:
NUMPY- 

In [4]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [103]:
a=[1,2,3,4,5]
for i in range(0,len(a)):
    a[i]=a[i]*2
print(a)

[2, 4, 6, 8, 10]


In [104]:
a=[1,2,3,"Python",4,5]
for i in range(0,len(a)):
    a[i]=a[i]*2
print(a)

[2, 4, 6, 'PythonPython', 8, 10]


In [105]:
# Create arrays
array1=np.array([1,2,3,4])

In [106]:
print(array1)

[1 2 3 4]


In [107]:
print(type(array1))

<class 'numpy.ndarray'>


In [108]:
print(array1.ndim)

1


In [109]:
print(array1.dtype)

int32


In [110]:
print(array1.shape)

(4,)


In [117]:
array2=np.zeros((4,),dtype="float")

In [118]:
print(array2)
print(array2.dtype)
print(array2.ndim)
print(array2.shape)
print(array2.size)

[0. 0. 0. 0.]
float64
1
(4,)
4


In [119]:
array2=np.arange(0,10,2,dtype=float)
print(array2)
print(array2.dtype)
print(array2.ndim)
print(array2.shape)
print(array2.size)

[0. 2. 4. 6. 8.]
float64
1
(5,)
5


In [123]:
array2=np.array([1,"2",3,4])
print(type(array2[0]))
print(array2.dtype)
print(array2.ndim)
print(array2.shape)
print(array2.size)

# all the integers will have corresponding string but not all the string will have corresponding integer

<class 'numpy.str_'>
<U11
1
(4,)
4


In [124]:
array2=np.linspace(0,100)

# 100-0/10

# 0 4 3
# 4-0/3
# 4-0/2

In [1]:
import numpy as np

In [8]:
array2=np.linspace(0,10,5)
print(array2,type(array2))

[ 0.   2.5  5.   7.5 10. ] <class 'numpy.ndarray'>


In [9]:
print(help(np.dtype))

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __mul__(self, value, /)
 |      Return self*value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __reduce__(...)
 |      Helper for pickle.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __rmul__(self, value, /)
 |      Return value*self.
 |  
 |  __setstate__(...)
 |  
 |  __str__(self, /)
 |      Return str(self).
 |  
 |  newbyteorder(...)
 |  

In [125]:
print(array2)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [127]:
array2=np.linspace(0,100,11,dtype=int)
print(array2)

[  0  10  20  30  40  50  60  70  80  90 100]


In [129]:
array2=np.random.rand(10)
print(array2)

[0.52416779 0.00659996 0.28897167 0.62199628 0.7720835  0.24694924
 0.57946239 0.67995255 0.43907259 0.24506327]


In [130]:
print(help(np.random.rand))

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [131]:
array2=np.random.randn(10)
print(array2)

[ 0.03986026  0.39626182  0.45728552 -1.34433906 -0.92498539 -0.7465631
  0.57699692 -0.37706302  1.08197502 -0.71009489]


In [132]:
print(help(np.random.randn))

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [135]:
array2=np.random.randint(0,10,10)

In [136]:
print(array2)

[1 9 3 7 8 1 2 1 2 9]
